In [1]:
import numpy as np


In [2]:
a= np.array([1,2,3])
print(a)
print(a.shape)
b= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(b)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
c=np.arange(1,10, .2)  #start , end, step
print(c)
print(c.shape)

d=np.linspace(1,10,20)
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [6]:
c


array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [7]:
print(c.reshape(9,5))

[[1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]
 [5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8]
 [7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8]
 [9.  9.2 9.4 9.6 9.8]]


In [8]:
print(c.reshape(3,3,5))


[[[1.  1.2 1.4 1.6 1.8]
  [2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]
  [6.  6.2 6.4 6.6 6.8]]

 [[7.  7.2 7.4 7.6 7.8]
  [8.  8.2 8.4 8.6 8.8]
  [9.  9.2 9.4 9.6 9.8]]]


In [9]:
np.random.randint(1,1000,(3,3))

array([[775, 155, 964],
       [499, 272, 721],
       [442, 273, 525]])

maths in  numpy


In [10]:
x=np.array([
    [1,2,3],
    [4,5,6],
])
y =np.array([
    [7,8,9],
    [4,5,6],
])




In [13]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)
print(x*2)

[[ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]]
[[ 7 16 27]
 [16 25 36]]
[[0.14285714 0.25       0.33333333]
 [1.         1.         1.        ]]
[[    1   256 19683]
 [  256  3125 46656]]
[[ 2  4  6]
 [ 8 10 12]]


In [15]:
#matrix multiplication
print(x.dot(y.T))
print(np.matmul(x,y.T))
print(x @ y.T)

[[ 50  32]
 [122  77]]
[[ 50  32]
 [122  77]]
[[ 50  32]
 [122  77]]


In [19]:
#statistical functions
print(x.sum())  #
print(x.mean())
print(x.sum(axis=0))  #sum of columns
print(x.sum(axis=1))  #sum of rows
print(x.std())       #
print(x.min())
print(x.max())
print(x.argmax())   #index of maximum
print(x.argmin())   #index of minimum


21
3.5
[5 7 9]
[ 6 15]
1.707825127659933
1
6
5
0


In [20]:
#trignomatic function
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))    #inverse sin


[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


In [21]:
#indexing
print(x[0,0])      #first row ,first column
print(x[0, :])     #first row ,all columns
print(x[:, 0])
print(x[:2, :2])
print(x[:2]) 

1
[1 2 3]
[1 4]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
